version: "3.9"
services:
  rtmp:
    build: ./
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server 
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./
    container_name: auth_server

  websocket-server:
    build: ./
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: production
    restart: always
